version: "3.8"

services:
  app:
    image: bojkikeva/securelogin-app:latest
    container_name: spring-boot-app
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1q84
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db

  db:
    image: bojkikeva/postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q84
      POSTGRES_DB: test_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
